openapi: 3.0.3
info:
  description: This is a set of interfaces based on the OpenAPI 3.0 specification
    for a wrapper client
  title: Swagger HIP Facade - OpenAPI 3.0
  version: 1.0.0
servers:
- url: http://localhost:8082/v1
paths:
  /add-patients:
    put:
      description: Insert or Update a list of patients
      operationId: upsertPatients
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/Patient'
              type: array
        description: Insert or update a list of patients in the wrapper database
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FacadeResponse'
          description: OK
        "400":
          description: Invalid request body supplied
        "404":
          description: Address not found
        "422":
          description: Validation exception
      summary: Insert or Update a list of patients
      tags:
      - patients
      x-content-type: application/json
      x-accepts: application/json
  /verify-otp:
    post:
      description: Verify OTP for link auth modes Mobile and Aadhaar
      operationId: verifyOTP
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/verifyOTP_request'
        description: Verifies OTP
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FacadeResponse'
          description: OK
        "400":
          description: Invalid request body supplied
        "404":
          description: Address not found
        "422":
          description: Validation exception
      summary: Verify OTP for link auth modes Mobile and Aadhaar
      tags:
      - link
      x-content-type: application/json
      x-accepts: application/json
  /link-carecontexts:
    post:
      description: Links care contexts for a given patient's abha address
      operationId: linkCareContexts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/linkCareContexts_request'
        description: Links Care Contexts
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FacadeResponse'
          description: OK
        "400":
          description: Invalid request body supplied
        "404":
          description: Address not found
        "422":
          description: Validation exception
      summary: Links care contexts for a given patient's abha address
      tags:
      - link
      x-content-type: application/json
      x-accepts: application/json
  /link-status/{requestId}:
    get:
      parameters:
      - description: Request Id of the link care context request.
        explode: false
        in: path
        name: requestId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestStatusResponse'
          description: OK
        "400":
          description: Invalid request body supplied
        "404":
          description: Address not found
        "422":
          description: Validation exception
      summary: Get status of Link request.
      tags:
      - link
      x-accepts: application/json
components:
  schemas:
    Patient:
      example:
        patientMobile: patientMobile
        gender: M
        patientReference: patientReference
        name: name
        dateOfBirth: 2003-09-23
        patientDisplay: patientDisplay
        abhaAddress: abhaAddress
      properties:
        abhaAddress:
          type: string
        name:
          type: string
        gender:
          enum:
          - M
          - F
          - O
          - U
          example: M
          type: string
        dateOfBirth:
          example: 2003-09-23
          type: string
        patientReference:
          type: string
        patientDisplay:
          type: string
        patientMobile:
          type: string
      type: object
    PatientWithCareContext:
      properties:
        id:
          description: ABHA Address
          type: string
        referenceNumber:
          type: string
        careContexts:
          items:
            $ref: '#/components/schemas/CareContext'
          type: array
      type: object
    CareContext:
      properties:
        referenceNumber:
          type: string
        display:
          type: string
      type: object
    RequestStatusResponse:
      example:
        error:
          code: 6
          message: message
        status: status
      properties:
        status:
          type: string
        error:
          $ref: '#/components/schemas/ErrorResponse'
      type: object
    FacadeResponse:
      example:
        code: 0
        clientRequestId: clientRequestId
        message: message
        error:
          code: 6
          message: message
      properties:
        clientRequestId:
          type: string
        code:
          type: integer
        message:
          type: string
        error:
          $ref: '#/components/schemas/ErrorResponse'
      type: object
    ErrorResponse:
      example:
        code: 6
        message: message
      properties:
        code:
          type: integer
        message:
          type: string
      type: object
    verifyOTP_request:
      properties:
        loginHint:
          enum:
          - hipLinking
          example: hipLinking
          type: string
        requestId:
          type: string
        authCode:
          type: string
      type: object
    linkCareContexts_request:
      properties:
        requestId:
          type: string
        requesterId:
          type: string
        abhaAddress:
          type: string
        authMode:
          enum:
          - DEMOGRAPHICS
          - MOBILE_OTP
          - AADHAAR_OTP
          example: DEMOGRAPHICS
          type: string
        patient:
          $ref: '#/components/schemas/PatientWithCareContext'
      type: object

